(() => {
  const URL='https://wmeuebjbvoqudhpwtxyn.supabase.co';
  const KEY='sb_publishable_jYrKnt_Unuv5M6XT1t0AaQ_quQTOpCD';
  const db=window.supabase?.createClient(URL,KEY),root=document.querySelector('#dashboard-view');
  if(!db||!root)return;
  const lang=()=>localStorage.getItem('preferredLanguage')||'en';
  const T={en:{delete:'Delete campaign',leave:'Leave campaign',titleDelete:'Delete campaign',titleLeave:'Leave campaign',confirmDelete:'This permanently deletes the campaign, its invitations and character links.',confirmLeave:'You will leave this campaign and your character will be unlinked.',type:'Type “supprimer” to confirm.',cancel:'Cancel',confirm:'Delete',confirmLeaveButton:'Leave',deleted:'Campaign deleted.',left:'You left the campaign.',error:'Unable to complete the action.'},fr:{delete:'Supprimer la campagne',leave:'Quitter la campagne',titleDelete:'Supprimer la campagne',titleLeave:'Quitter la campagne',confirmDelete:'Cette action supprime définitivement la campagne, ses invitations et les liens avec les personnages.',confirmLeave:'Vous quitterez cette campagne et votre personnage sera détaché.',type:'Saisissez « supprimer » pour confirmer.',cancel:'Annuler',confirm:'Supprimer',confirmLeaveButton:'Quitter',deleted:'Campagne supprimée.',left:'Vous avez quitté la campagne.',error:'Impossible d’effectuer cette action.'}};
  const t=k=>T[lang()][k]||k,esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const style=document.createElement('style');style.textContent=`
    .mj-campaign-management{display:flex;justify-content:flex-end;align-items:center;gap:8px;margin-top:14px;padding-top:12px;border-top:1px solid var(--border);}
    .mj-campaign-management::before{content:'⚙';margin-right:auto;opacity:.55;font-size:.9rem}
    .mj-campaign-danger{border-color:rgba(180,70,50,.55)!important;color:#e9b5a6!important;background:rgba(100,35,25,.16)!important}
    .mj-campaign-danger:hover{border-color:#c98270!important;background:rgba(120,40,25,.28)!important}
    .mj-campaign-confirm{position:fixed;inset:0;z-index:12000;display:flex;align-items:center;justify-content:center;padding:20px}
    .mj-campaign-confirm-backdrop{position:absolute;inset:0;background:rgba(12,7,4,.78);backdrop-filter:blur(4px)}
    .mj-campaign-confirm-card{position:relative;width:min(520px,100%);padding:26px;border-radius:18px;background:linear-gradient(145deg,#261b13,#17100c);border:1px solid rgba(201,157,76,.6);box-shadow:0 24px 80px rgba(0,0,0,.55)}
    .mj-campaign-confirm-card h3{margin-top:0;color:var(--accent,#c99d4c)}
    .mj-campaign-confirm-card .campaign-warning{padding:12px 14px;margin:14px 0;border-left:3px solid var(--accent,#c99d4c);background:rgba(201,157,76,.08);border-radius:8px;line-height:1.5}
    .mj-campaign-confirm-card input{width:100%;margin:8px 0 16px}
    .mj-campaign-confirm-actions{display:flex;gap:8px;justify-content:flex-end;flex-wrap:wrap}
  `;document.head.appendChild(style);
  let user=null;
  async function getUser(){const {data}=await db.auth.getSession();user=data.session?.user||null;return user}
  async function roleFor(id){if(!user)return null;const {data}=await db.from('campaigns').select('owner_user_id').eq('id',id).maybeSingle();if(data?.owner_user_id===user.id)return'gm';const {data:m}=await db.from('campaign_members').select('role').eq('campaign_id',id).eq('user_id',user.id).eq('status','active').maybeSingle();return m?.role||null}
  async function decorate(){if(!user)return;root.querySelectorAll('#mj-campaigns .mj-card').forEach(async card=>{if(card.querySelector('.mj-campaign-management'))return;const b=card.querySelector('.mj-open');const id=b?.dataset.id;if(!id)return;const role=await roleFor(id);if(role!=='gm'&&role!=='player')return;const wrap=document.createElement('div');wrap.className='mj-campaign-management';wrap.innerHTML=`<button type="button" class="button button-secondary mj-campaign-danger">${role==='gm'?t('delete'):t('leave')}</button>`;card.appendChild(wrap);wrap.querySelector('button').onclick=()=>confirmAction(id,role,card.querySelector('h3')?.textContent?.trim()||'campaign')})}
  function confirmAction(id,role,name){const deleting=role==='gm',modal=document.createElement('div');modal.className='mj-campaign-confirm';modal.innerHTML=`<div class="mj-campaign-confirm-backdrop"></div><section class="mj-campaign-confirm-card" role="dialog" aria-modal="true"><p class="eyebrow">${deleting?'⚠':'↪'}</p><h3>${deleting?t('titleDelete'):t('titleLeave')}</h3><p><strong>${esc(name)}</strong></p><div class="campaign-warning">${deleting?t('confirmDelete'):t('confirmLeave')}<br><strong>${t('type')}</strong></div><input autocomplete="off" placeholder="supprimer" aria-label="supprimer"><div class="mj-campaign-confirm-actions"><button type="button" class="button button-secondary" data-cancel>${t('cancel')}</button><button type="button" class="button ${deleting?'button-danger':'button-primary'}" data-ok disabled>${deleting?t('confirm'):t('confirmLeaveButton')}</button></div></section>`;document.body.appendChild(modal);const input=modal.querySelector('input'),ok=modal.querySelector('[data-ok]'),close=()=>modal.remove();input.oninput=()=>ok.disabled=input.value.trim().toLowerCase()!=='supprimer';modal.querySelector('[data-cancel]').onclick=close;modal.querySelector('.mj-campaign-confirm-backdrop').onclick=close;input.onkeydown=e=>{if(e.key==='Escape')close();if(e.key==='Enter'&&!ok.disabled)ok.click()};ok.onclick=async()=>{ok.disabled=true;const {error}=await db.rpc(deleting?'delete_campaign':'leave_campaign',{p_campaign_id:id});if(error){alert(error.message||t('error'));ok.disabled=false;return}close();const message=root.querySelector('#mj-msg');if(message){message.textContent=deleting?t('deleted'):t('left');message.className='status-message success'}const card=[...root.querySelectorAll('#mj-campaigns .mj-card')].find(c=>c.querySelector(`.mj-open[data-id="${CSS.escape(id)}"]`));if(card)card.remove()};input.focus()}
  async function init(){if(!await getUser())return;decorate();const target=root.querySelector('#mj-campaigns')||root;new MutationObserver(()=>decorate()).observe(target,{childList:true,subtree:true});window.addEventListener('language-changed',()=>setTimeout(decorate,0))}init();
})();