(() => {
  const URL='https://wmeuebjbvoqudhpwtxyn.supabase.co';
  const KEY='sb_publishable_jYrKnt_Unuv5M6XT1t0AaQ_quQTOpCD';
  const db=window.supabase?.createClient(URL,KEY);
  const root=document.querySelector('#dashboard-view');
  if(!db||!root)return;
  const lang=()=>localStorage.getItem('preferredLanguage')||'en';
  const T={en:{title:'My campaigns',empty:'No campaigns.',gm:'GM',player:'Player',delete:'Delete campaign',leave:'Leave campaign',titleDelete:'Delete campaign',titleLeave:'Leave campaign',confirmDelete:'This action cannot be undone. Type "supprimer" to confirm.',confirmLeave:'Type "supprimer" to confirm leaving this campaign.',cancel:'Cancel',confirm:'Confirm',deleted:'Campaign deleted.',left:'You left the campaign.',error:'Unable to complete the action.'},fr:{title:'Mes campagnes',empty:'Aucune campagne.',gm:'MJ',player:'Joueur',delete:'Supprimer la campagne',leave:'Quitter la campagne',titleDelete:'Supprimer la campagne',titleLeave:'Quitter la campagne',confirmDelete:'Cette action est irréversible. Saisissez « supprimer » pour confirmer.',confirmLeave:'Saisissez « supprimer » pour confirmer que vous voulez quitter cette campagne.',cancel:'Annuler',confirm:'Confirmer',deleted:'Campagne supprimée.',left:'Vous avez quitté la campagne.',error:'Impossible d’effectuer cette action.'}};
  const t=k=>T[lang()][k]||k; const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
  let user=null,box=null;
  const style=document.createElement('style');style.textContent='.campaign-management{margin:24px 0;padding:18px;border:1px solid var(--border,#374151);border-radius:16px;background:rgba(17,24,39,.55)}.campaign-management-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:12px;margin-top:12px}.campaign-management-item{padding:14px;border:1px solid var(--border,#374151);border-radius:12px;background:rgba(31,41,55,.5)}.campaign-danger{border-color:#7f1d1d!important}.campaign-confirm{position:fixed;inset:0;z-index:12000;display:flex;align-items:center;justify-content:center;padding:16px}.campaign-confirm-backdrop{position:absolute;inset:0;background:rgba(0,0,0,.72)}.campaign-confirm-card{position:relative;width:min(480px,100%);padding:20px;border-radius:16px;background:var(--surface,#111827);border:1px solid var(--border,#374151)}.campaign-confirm-card input{width:100%;margin:12px 0}.campaign-confirm-actions{display:flex;gap:8px;justify-content:flex-end;flex-wrap:wrap}';document.head.appendChild(style);
  function render(){if(box)box.remove();if(!user)return;box=document.createElement('section');box.className='campaign-management';box.innerHTML=`<h2>${t('title')}</h2><div class="campaign-management-list"><p class="muted">…</p></div>`;root.insertBefore(box,root.querySelector('#characters-list')||root.firstElementChild);load();}
  async function load(){if(!box)return;const list=box.querySelector('.campaign-management-list');const [owned,members]=await Promise.all([db.from('campaigns').select('id,name,description').eq('owner_user_id',user.id).order('created_at',{ascending:false}),db.from('campaign_members').select('campaign_id,role').eq('user_id',user.id).eq('role','player').eq('status','active')]);if(owned.error||members.error){list.innerHTML=`<p class="status-message error">${esc((owned.error||members.error).message)}</p>`;return;}const ids=(members.data||[]).map(x=>x.campaign_id);let joined=[];if(ids.length){const r=await db.from('campaigns').select('id,name,description').in('id',ids);if(r.error){list.innerHTML=`<p class="status-message error">${esc(r.error.message)}</p>`;return;}joined=r.data||[];}const rows=[...(owned.data||[]).map(x=>({...x,role:'gm'})),...joined.map(x=>({...x,role:'player'}))];if(!rows.length){list.innerHTML=`<p class="muted">${t('empty')}</p>`;return;}list.innerHTML=rows.map(c=>`<article class="campaign-management-item ${c.role==='gm'?'campaign-danger':''}"><h3>${esc(c.name)}</h3><p class="muted">${c.role==='gm'?t('gm'):t('player')}${c.description?` · ${esc(c.description)}`:''}</p><button type="button" class="button button-secondary campaign-delete-button" data-id="${c.id}" data-role="${c.role}" data-name="${esc(c.name)}">${c.role==='gm'?t('delete'):t('leave')}</button></article>`).join('');list.querySelectorAll('.campaign-delete-button').forEach(b=>b.onclick=()=>confirmAction(b.dataset.id,b.dataset.role,b.dataset.name));}
  function confirmAction(id,role,name){const deleting=role==='gm';const modal=document.createElement('div');modal.className='campaign-confirm';modal.innerHTML=`<div class="campaign-confirm-backdrop"></div><section class="campaign-confirm-card" role="dialog" aria-modal="true"><h3>${deleting?t('titleDelete'):t('titleLeave')}</h3><p>${deleting?t('confirmDelete'):t('confirmLeave')}</p><input id="campaign-confirm-input" autocomplete="off" placeholder="supprimer"><div class="campaign-confirm-actions"><button type="button" class="button button-secondary" id="campaign-confirm-cancel">${t('cancel')}</button><button type="button" class="button button-primary" id="campaign-confirm-ok" disabled>${t('confirm')}</button></div></section>`;document.body.appendChild(modal);const input=modal.querySelector('#campaign-confirm-input'),ok=modal.querySelector('#campaign-confirm-ok');input.oninput=()=>{ok.disabled=input.value.trim().toLowerCase()!=='supprimer'};const close=()=>modal.remove();modal.querySelector('#campaign-confirm-cancel').onclick=close;modal.querySelector('.campaign-confirm-backdrop').onclick=close;ok.onclick=async()=>{ok.disabled=true;const r=await db.rpc(deleting?'delete_campaign':'leave_campaign',{p_campaign_id:id});if(r.error){alert(r.error.message||t('error'));ok.disabled=false;return;}close();load();const message=root.querySelector('#mj-msg');if(message){message.textContent=deleting?t('deleted'):t('left');message.className='status-message success';}};input.focus();}
  async function init(){const s=await db.auth.getSession();user=s.data.session?.user||null;if(user)render();}db.auth.onAuthStateChange((_e,s)=>{user=s?.user||null;if(user)render();else if(box){box.remove();box=null;}});window.addEventListener('language-changed',()=>{if(user)render();});init();
})();