(() => {
  const URL='https://wmeuebjbvoqudhpwtxyn.supabase.co';
  const KEY='sb_publishable_jYrKnt_Unuv5M6XT1t0AaQ_quQTOpCD';
  const db=window.supabase.createClient(URL,KEY);
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const labels={en:{asi:'Ability Score Improvement',choose:'Choose a feat',save:'Apply',saved:'Feat saved.',remove:'Choice removed.'},fr:{asi:'Amélioration de caractéristique',choose:'Choisir un don',save:'Appliquer',saved:'Don enregistré.',remove:'Choix supprimé.'}};
  async function ctx(){const {data:{user}}=await db.auth.getUser();const name=document.querySelector('#sheet-name')?.value?.trim();if(!user||!name)return null;const {data,error}=await db.from('characters').select('id,level').eq('user_id',user.id).eq('name',name).maybeSingle();return error||!data?null:{user,character:data};}
  async function choice(id,key,level){const {data}=await db.from('character_feature_choices').select('id,choice_value').eq('character_id',id).eq('feature_key',`${key}_level_${level}`).limit(1);return data?.[0]||null;}
  async function attach(select){if(select.dataset.featEnhanced)return;select.dataset.featEnhanced='1';const c=await ctx();if(!c)return;const level=Number(select.dataset.level), featureKey=select.dataset.featureKey;const lang=localStorage.getItem('preferredLanguage')||'en',l=labels[lang];const saved=await choice(c.character.id,featureKey,level);const wrap=document.createElement('div');wrap.className='feat-controls';wrap.innerHTML=`<select class="feat-select"><option value="">${l.choose}</option></select><button type="button" class="button button-primary feat-apply">${l.save}</button><small class="feat-status"></small>`;select.parentElement.appendChild(wrap);const fs=wrap.querySelector('.feat-select'),status=wrap.querySelector('.feat-status');const {data:feats}=await db.from('feat_catalog').select('feat_key,name_en,name_fr,category,min_level,repeatable').or('category.eq.general,category.eq.epic_boon').lte('min_level',level).order('name_en');(feats||[]).forEach(f=>{const o=document.createElement('option');o.value=f.feat_key;o.textContent=lang==='fr'?f.name_fr:f.name_en;fs.appendChild(o);});if(saved){try{const v=JSON.parse(saved.choice_value||'{}');if(v.feat_key)fs.value=v.feat_key;}catch{}}
    select.addEventListener('change',async()=>{if(select.value==='ability_score_improvement'){await db.from('character_feats').delete().eq('character_id',c.character.id).eq('source_feature_key',featureKey).eq('source_level',level);return;}await db.from('character_feature_choices').update({choice_value:JSON.stringify({type:select.value})}).eq('id',(await choice(c.character.id,featureKey,level))?.id);});
    wrap.querySelector('.feat-apply').addEventListener('click',async()=>{try{if(!fs.value){status.textContent='';return;}const payload={character_id:c.character.id,feature_key:fs.value,source_feature_key:featureKey,source_level:level,metadata:{source:'feat-picker.js'}};const old=await choice(c.character.id,featureKey,level);if(old)await db.from('character_feature_choices').update({choice_value:JSON.stringify({type:'feat',feat_key:fs.value})}).eq('id',old.id);else await db.from('character_feature_choices').insert({character_id:c.character.id,feature_key:`${featureKey}_level_${level}`,choice_value:JSON.stringify({type:'feat',feat_key:fs.value}),metadata:{source:'feat-picker.js'}});await db.from('character_feats').upsert(payload,{onConflict:'character_id,source_feature_key,source_level'});status.textContent=l.saved;}catch(e){status.textContent=e.message;status.className='feat-status error';}});
  }
  function scan(){document.querySelectorAll('#progression-features select[data-choice-role="type"]').forEach(s=>{if(['asi_or_feat','epic_boon_or_feat'].includes(s.dataset.choiceType)||s.value==='feat')attach(s);});}
  new MutationObserver(scan).observe(document.body,{childList:true,subtree:true});document.addEventListener('change',e=>{if(e.target.matches('#sheet-level,#sheet-name'))setTimeout(scan,150)});const st=document.createElement('style');st.textContent='.feat-controls{margin-top:7px;padding:9px;background:var(--surface-2);border:1px solid var(--border);border-radius:10px;display:grid;gap:7px}.feat-controls select{margin:0}.feat-status{min-height:16px}.feat-status.error{color:var(--danger)}';document.head.appendChild(st);
})();
