(() => {
  const URL='https://wmeuebjbvoqudhpwtxyn.supabase.co',KEY='sb_publishable_jYrKnt_Unuv5M6XT1t0AaQ_quQTOpCD',db=window.supabase.createClient(URL,KEY);
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const labels={en:{choose:'Choose a feat',save:'Apply',saved:'Feat saved.'},fr:{choose:'Choisir un don',save:'Appliquer',saved:'Don enregistré.'}};
  async function ctx(){const {data:{user}}=await db.auth.getUser();const name=document.querySelector('#sheet-name')?.value?.trim();if(!user||!name)return null;const {data,error}=await db.from('characters').select('id,level,spellcasting_ability_key').eq('user_id',user.id).eq('name',name).maybeSingle();return error||!data?null:{character:data};}
  async function choice(id,key,level){const {data}=await db.from('character_feature_choices').select('id,choice_value').eq('character_id',id).eq('feature_key',`${key}_level_${level}`).limit(1);return data?.[0]||null;}
  async function attach(select){if(select.dataset.featEnhanced)return;const options=[...select.options].map(o=>o.value);if(!options.includes('feat')&&!options.includes('epic_boon'))return;select.dataset.featEnhanced='1';const c=await ctx();if(!c)return;const level=Number(select.dataset.level),featureKey=select.dataset.featureKey,lang=localStorage.getItem('preferredLanguage')||'en',l=labels[lang];const saved=await choice(c.character.id,featureKey,level);const wrap=document.createElement('div');wrap.className='feat-controls';wrap.innerHTML=`<select class="feat-select"><option value="">${l.choose}</option></select><button type="button" class="button button-primary feat-apply">${l.save}</button><small class="feat-status"></small>`;select.parentElement.appendChild(wrap);const fs=wrap.querySelector('.feat-select'),status=wrap.querySelector('.feat-status');
    async function load(type){fs.innerHTML=`<option value="">${l.choose}</option>`;const category=type==='epic_boon'?'epic_boon':'general';let q=db.from('feat_catalog').select('feat_key,name_en,name_fr,category,min_level,repeatable').eq('category',category).lte('min_level',level).order('name_en');const {data:feats}=await q;(feats||[]).forEach(f=>{const o=document.createElement('option');o.value=f.feat_key;o.textContent=lang==='fr'?f.name_fr:f.name_en;fs.appendChild(o);});if(saved){try{const v=JSON.parse(saved.choice_value||'{}');if(v.feat_key&&v.type===type)fs.value=v.feat_key;}catch{}}}
    await load(select.value);
    select.addEventListener('change',async()=>{const type=select.value;if(type==='ability_score_improvement'){await db.from('character_feats').delete().eq('character_id',c.character.id).eq('source_feature_key',featureKey).eq('source_level',level);const old=await choice(c.character.id,featureKey,level);if(old)await db.from('character_feature_choices').update({choice_value:JSON.stringify({type:'ability_score_improvement'}),metadata:{selection:'asi'}}).eq('id',old.id);return;}if(type==='feat'||type==='epic_boon'){await load(type);}});
    wrap.querySelector('.feat-apply').addEventListener('click',async()=>{if(!fs.value)return;const type=select.value||'feat';const payload={character_id:c.character.id,feat_key:fs.value,source_feature_key:featureKey,source_level:level,metadata:{source:'feat-picker.js',category:type}};const {error}=await db.from('character_feats').upsert(payload,{onConflict:'character_id,source_feature_key,source_level'});if(error){status.textContent=error.message;status.className='feat-status error';return;}const old=await choice(c.character.id,featureKey,level),value=JSON.stringify({type,feat_key:fs.value});if(old)await db.from('character_feature_choices').update({choice_value:value,metadata:{source:'feat-picker.js',feat_key:fs.value}}).eq('id',old.id);else await db.from('character_feature_choices').insert({character_id:c.character.id,feature_key:`${featureKey}_level_${level}`,choice_value:value,metadata:{source:'feat-picker.js',feat_key:fs.value}});status.textContent=l.saved;});
  }
  function scan(){document.querySelectorAll('#progression-features select[data-choice-role="type"]').forEach(attach);}
  new MutationObserver(scan).observe(document.body,{childList:true,subtree:true});document.addEventListener('change',e=>{if(e.target.matches('#sheet-level,#sheet-name'))setTimeout(scan,150);});const st=document.createElement('style');st.textContent='.feat-controls{margin-top:7px;padding:9px;background:var(--surface-2);border:1px solid var(--border);border-radius:10px;display:grid;gap:7px}.feat-controls select{margin:0}.feat-status{min-height:16px}.feat-status.error{color:var(--danger)}';document.head.appendChild(st);
})();