(() => {
  const URL='https://wmeuebjbvoqudhpwtxyn.supabase.co',KEY='sb_publishable_jYrKnt_Unuv5M6XT1t0AaQ_quQTOpCD',db=window.supabase.createClient(URL,KEY);
  const CLASSES=['barbarian','bard','cleric','druid','fighter','monk','paladin','ranger','rogue','sorcerer','warlock','wizard'];
  const ABILITY={barbarian:['strength'],bard:['charisma'],cleric:['wisdom'],druid:['wisdom'],fighter:['strength','dexterity'],monk:['dexterity','wisdom'],paladin:['strength','charisma'],ranger:['dexterity','wisdom'],rogue:['dexterity'],sorcerer:['charisma'],warlock:['charisma'],wizard:['intelligence']};
  const LABEL={en:{barbarian:'Barbarian',bard:'Bard',cleric:'Cleric',druid:'Druid',fighter:'Fighter',monk:'Monk',paladin:'Paladin',ranger:'Ranger',rogue:'Rogue',sorcerer:'Sorcerer',warlock:'Warlock',wizard:'Wizard'},fr:{barbarian:'Barbare',bard:'Barde',cleric:'Clerc',druid:'Druide',fighter:'Guerrier',monk:'Moine',paladin:'Paladin',ranger:'Rôdeur',rogue:'Roublard',sorcerer:'Ensorceleur',warlock:'Occultiste',wizard:'Magicien'}};
  async function context(){const {data:{user}}=await db.auth.getUser();const name=document.querySelector('#sheet-name')?.value?.trim();if(!user||!name)return null;const {data:character}=await db.from('characters').select('id,class_key,level').eq('user_id',user.id).eq('name',name).maybeSingle();if(!character)return null;const {data:scores}=await db.from('character_ability_scores').select('*').eq('character_id',character.id).single();return{character,scores:scores||{}};}
  function eligible(c,cls){return ABILITY[cls].every(a=>Number(c.scores[a]||10)>=13)}
  async function render(){const stats=document.querySelector('#progression-stats');if(!stats)return;let panel=document.querySelector('#multiclass-panel');if(!panel){panel=document.createElement('div');panel.id='multiclass-panel';stats.insertAdjacentElement('afterend',panel);}const c=await context();if(!c){panel.innerHTML='';return;}const {data:rows}=await db.from('character_classes').select('class_key,class_level').eq('character_id',c.character.id).order('class_key');const map=Object.fromEntries((rows||[]).map(r=>[r.class_key,Number(r.class_level)]));if(!Object.keys(map).length)map[c.character.class_key]=Number(c.character.level||1);const total=Number(c.character.level||1),lang=localStorage.getItem('preferredLanguage')||'en',fr=lang==='fr';panel.innerHTML=`<div class="multiclass-box"><div class="progression-feature-title">${fr?'Multiclasse':'Multiclassing'}</div><p class="progression-note">${fr?'Niveau total':'Total level'}: <strong>${total}</strong> / 20</p><div class="multiclass-grid">${CLASSES.map(cls=>{const lv=map[cls]||0;const ok=eligible(c,cls);return `<label><span>${LABEL[lang][cls]}${ok?'':' 🔒'}</span><input type="number" min="0" max="20" value="${lv}" data-mc-class="${cls}" ${lv===0&&!ok?'disabled':''}></label>`}).join('')}</div><label class="multiclass-primary"><span>${fr?'Classe principale':'Primary class'}</span><select id="multiclass-primary">${CLASSES.map(cls=>`<option value="${cls}" ${cls===c.character.class_key?'selected':''}>${LABEL[lang][cls]}</option>`).join('')}</select></label><button type="button" class="button button-primary" id="multiclass-save">${fr?'Enregistrer les niveaux':'Save class levels'}</button><small id="multiclass-status"></small></div>`;
    panel.querySelector('#multiclass-save').addEventListener('click',async()=>{const inputs=[...panel.querySelectorAll('[data-mc-class]')],next=Object.fromEntries(inputs.map(i=>[i.dataset.mcClass,Math.max(0,Math.min(20,Number(i.value)||0))]));const sum=Object.values(next).reduce((a,b)=>a+b,0),status=panel.querySelector('#multiclass-status'),primary=panel.querySelector('#multiclass-primary').value;if(sum!==total){status.textContent=fr?`La somme doit être exactement ${total}.`:`The class levels must total exactly ${total}.`;return;}if(next[primary]<1){status.textContent=fr?'La classe principale doit avoir au moins 1 niveau.':'Primary class must have at least 1 level.';return;}for(const cls of CLASSES)if(next[cls]>0&&!eligible(c,cls)){status.textContent=fr?`Prérequis insuffisants pour ${LABEL[lang][cls]}.`:`Prerequisites not met for ${LABEL[lang][cls]}.`;return;}await db.from('character_classes').delete().eq('character_id',c.character.id);const payload=Object.entries(next).filter(([,lv])=>lv>0).map(([class_key,class_level])=>({character_id:c.character.id,class_key,class_level}));if(payload.length)await db.from('character_classes').insert(payload);const {error}=await db.from('characters').update({class_key:primary}).eq('id',c.character.id);if(error){status.textContent=error.message;return;}status.textContent=fr?'Multiclasse enregistrée.':'Multiclass levels saved.';window.dispatchEvent(new CustomEvent('character-multiclass-applied',{detail:{classes:next,primary}}));});}
  let timer;const schedule=()=>{clearTimeout(timer);timer=setTimeout(render,120)};new MutationObserver(r=>{if(r.some(x=>!x.target.closest?.('#multiclass-panel')))schedule()}).observe(document.body,{childList:true,subtree:true});document.addEventListener('change',e=>{if(e.target.matches('#sheet-level,#sheet-name,#score-strength,#score-dexterity,#score-wisdom,#score-charisma,#score-intelligence'))schedule()});schedule();
  const st=document.createElement('style');st.textContent='.multiclass-box{margin:12px 0;padding:12px;border:1px solid var(--border);border-radius:12px;background:var(--surface-2)}.multiclass-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px;margin:10px 0}.multiclass-grid label,.multiclass-primary{display:grid;gap:4px}.multiclass-grid input{width:100%}.multiclass-primary{margin-bottom:8px}.multiclass-box small{min-height:18px}@media(max-width:700px){.multiclass-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}';document.head.appendChild(st);
})();