const PROGRESSION_URL='https://wmeuebjbvoqudhpwtxyn.supabase.co';
const PROGRESSION_KEY='sb_publishable_jYrKnt_Unuv5M6XT1t0AaQ_quQTOpCD';
const {createClient:createProgressionClient}=window.supabase;
const progressionSupabase=createProgressionClient(PROGRESSION_URL,PROGRESSION_KEY);
const LEVEL_XP=[0,300,900,2700,6500,14000,23000,34000,48000,64000,85000,100000,120000,140000,165000,195000,225000,265000,305000,355000];
const CLASS_DATA={barbarian:{die:12,fixed:7},fighter:{die:10,fixed:6},paladin:{die:10,fixed:6},ranger:{die:10,fixed:6},bard:{die:8,fixed:5},cleric:{die:8,fixed:5},druid:{die:8,fixed:5},monk:{die:8,fixed:5},rogue:{die:8,fixed:5},warlock:{die:8,fixed:5},sorcerer:{die:6,fixed:4},wizard:{die:6,fixed:4}};
const CLASS_LABELS={en:{barbarian:'Barbarian',bard:'Bard',cleric:'Cleric',druid:'Druid',fighter:'Fighter',monk:'Monk',paladin:'Paladin',ranger:'Ranger',rogue:'Rogue',sorcerer:'Sorcerer',warlock:'Warlock',wizard:'Wizard'},fr:{barbarian:'Barbare',bard:'Barde',cleric:'Clerc',druid:'Druide',fighter:'Guerrier',monk:'Moine',paladin:'Paladin',ranger:'Rôdeur',rogue:'Roublard',sorcerer:'Ensorceleur',warlock:'Occultiste',wizard:'Magicien'}};
const abilityMod=score=>Math.floor((Number(score??10)-10)/2);
const xpForLevel=level=>LEVEL_XP[Math.max(1,Math.min(20,Number(level)||1))-1];
function fixedHpMax(classKey,level,conScore){const data=CLASS_DATA[classKey]||CLASS_DATA.fighter;const con=abilityMod(conScore);return Math.max(level,data.die+con+Math.max(0,level-1)*Math.max(1,data.fixed+con));}
function nextLevelInfo(level,xp){if(level>=20)return{next:null,remaining:0};const target=LEVEL_XP[level];return{next:level+1,remaining:Math.max(0,target-Number(xp||0))};}
function labelForFeature(name,fr){const labels={'Lay On Hands':fr?'Imposition des mains':'Lay On Hands','Spellcasting':fr?'Incantation':'Spellcasting','Weapon Mastery':fr?'Maîtrise des armes':'Weapon Mastery','Fighting Style':fr?'Style de combat':'Fighting Style',"Paladin's Smite":fr?'Châtiment du paladin':"Paladin's Smite",'Channel Divinity':fr?'Conduit divin':'Channel Divinity','Paladin Subclass':fr?'Sous-classe de paladin':'Paladin Subclass','Ability Score Improvement':fr?'Amélioration de caractéristique':'Ability Score Improvement','Extra Attack':fr?'Attaque supplémentaire':'Extra Attack','Faithful Steed':fr?'Destrier fidèle':'Faithful Steed','Aura of Protection':fr?'Aura de protection':'Aura of Protection','Abjure Foes':fr?'Abjurer les ennemis':'Abjure Foes','Aura of Courage':fr?'Aura de courage':'Aura of Courage','Radiant Strikes':fr?'Frappes radiantes':'Radiant Strikes','Restoring Touch':fr?'Toucher restaurateur':'Restoring Touch','Aura Expansion':fr?'Extension des auras':'Aura Expansion','Epic Boon':fr?'Don épique':'Epic Boon','Arcane Recovery':fr?'Récupération des arcanes':'Arcane Recovery','Ritual Adept':fr?'Adepte des rituels':'Ritual Adept','Scholar':fr?'Érudit':'Scholar','Wizard Subclass':fr?'Sous-classe de magicien':'Wizard Subclass','Memorize Spell':fr?'Mémoriser un sort':'Memorize Spell','Spell Mastery':fr?'Maîtrise des sorts':'Spell Mastery','Subclass Feature':fr?'Capacité de sous-classe':'Subclass Feature'};return labels[name]||name;}
async function getCatalog(category){let q=progressionSupabase.from('feat_catalog').select('feat_key,name_en,name_fr,category,min_level,repeatable').order('name_en');if(category)q=q.eq('category',category);const {data,error}=await q;if(error)throw error;return data||[];}
async function getSubclassOptions(classKey){const {data,error}=await progressionSupabase.from('subclass_catalog').select('subclass_key,name').eq('class_key',classKey).order('name');if(error)throw error;return data||[];}
const choiceStorageKey=(featureKey,level)=>`${featureKey}_level_${level}`;
async function saveFeatureChoice(characterId,featureKey,level,value,metadata={}){if(!value)return;const storageKey=choiceStorageKey(featureKey,level);const {data:existing}=await progressionSupabase.from('character_feature_choices').select('id').eq('character_id',characterId).eq('feature_key',storageKey).limit(1);const first=existing?.[0];if(first)await progressionSupabase.from('character_feature_choices').update({choice_value:value,metadata:{source:'progression-ui',...metadata}}).eq('id',first.id);else await progressionSupabase.from('character_feature_choices').insert({character_id:characterId,feature_key:storageKey,choice_value:value,metadata:{source:'progression-ui',...metadata}});await renderProgression();}
function esc(value){return String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}
function choiceSelect(options,current,placeholder,attrs=''){return `<select ${attrs}><option value="">${placeholder}</option>${options.map(o=>`<option value="${esc(o.value)}" ${o.value===current?'selected':''}>${esc(o.label)}</option>`).join('')}</select>`;}
async function renderFeatureProgression(character,level,fr){const box=document.querySelector('#progression-features');if(!box)return;const [{data:features},{data:choices},subclassRows,allFeats,fightingStyles]=await Promise.all([progressionSupabase.from('class_progression').select('level,feature_key,feature_name,choice_type,metadata').eq('class_key',character.class_key).lte('level',level).order('level').order('feature_key'),progressionSupabase.from('character_feature_choices').select('feature_key,choice_value,metadata').eq('character_id',character.id),getSubclassOptions(character.class_key),getCatalog(),getCatalog('fighting_style')]);const choiceMap=new Map((choices||[]).map(c=>[c.feature_key,c]));if(!features?.length){box.innerHTML='';return;}const groups=new Map();features.forEach(f=>{if(!groups.has(f.level))groups.set(f.level,[]);groups.get(f.level).push(f);});
const featOptions=allFeats.filter(f=>f.category!=='fighting_style').map(f=>({value:f.feat_key,label:fr?f.name_fr:f.name_en}));
const epicOptions=allFeats.filter(f=>f.category==='epic_boon').map(f=>({value:f.feat_key,label:fr?f.name_fr:f.name_en}));
const styleOptions=fightingStyles.map(f=>({value:f.feat_key,label:fr?f.name_fr:f.name_en}));
box.innerHTML=`<div class="progression-feature-title">${fr?'Capacités acquises':'Class features'}</div>`+Array.from(groups.entries()).reverse().map(([lv,items])=>`<div class="progression-level"><strong>Lv ${lv}</strong><div class="progression-feature-list">${items.map(f=>{const storageKey=choiceStorageKey(f.feature_key,f.level);const saved=choiceMap.get(storageKey);let current=saved?.choice_value||'';let body='';if(f.choice_type==='subclass'){body=choiceSelect(subclassRows.map(v=>({value:v.subclass_key,label:v.name})),current,fr?'Choisir…':'Choose…',`data-feature-key="${esc(f.feature_key)}" data-level="${f.level}"`);}else if(f.choice_type==='choice'&&f.feature_key==='fighting_style'){body=choiceSelect(styleOptions,current,fr?'Choisir un style…':'Choose a style…',`data-feature-key="${esc(f.feature_key)}" data-level="${f.level}"`);}else if(f.choice_type==='asi_or_feat'||f.choice_type==='epic_boon_or_feat'||f.choice_type==='feat'){let parsed={type:current,feat:''};try{if(current.startsWith('{'))parsed=JSON.parse(current);}catch{}const typeOptions=f.choice_type==='epic_boon_or_feat'?[{value:'epic_boon',label:fr?'Don épique':'Epic Boon'},{value:'feat',label:fr?'Don':'Feat'}]:f.choice_type==='asi_or_feat'?[{value:'ability_score_improvement',label:fr?'Amélioration de caractéristique':'Ability Score Improvement'},{value:'feat',label:fr?'Don':'Feat'}]:[{value:'feat',label:fr?'Don':'Feat'}];body=`<div class="progression-choice-stack">${choiceSelect(typeOptions,parsed.type,fr?'Choisir…':'Choose…',`data-feature-key="${esc(f.feature_key)}" data-level="${f.level}" data-choice-role="type"`)}<select data-feature-key="${esc(f.feature_key)}" data-level="${f.level}" data-choice-role="feat" class="${parsed.type==='feat'||parsed.type==='epic_boon'?'':'hidden'}"><option value="">${fr?'Choisir le don…':'Choose feat…'}</option>${(parsed.type==='epic_boon'?epicOptions:featOptions).map(o=>`<option value="${esc(o.value)}" ${o.value===parsed.feat?'selected':''}>${esc(o.label)}</option>`).join('')}</select></div>`;}else if(f.choice_type==='choice'&&f.feature_key==='scholar'){const opts=(f.metadata?.expertise_skill_options||[]).map(v=>({value:v,label:v.replaceAll('_',' ')}));body=choiceSelect(opts,current,fr?'Choisir…':'Choose…',`data-feature-key="${esc(f.feature_key)}" data-level="${f.level}"`);}else{body=`<small>${f.choice_type==='resource'&&f.metadata?.count?`${fr?'Uses':'Uses'}: ${f.metadata.count}`:''}</small>`;}return `<div class="progression-feature"><span>${labelForFeature(f.feature_name,fr)}</span>${body}</div>`;}).join('')}</div></div>`).join('');
box.querySelectorAll('select[data-choice-role="type"]').forEach(select=>select.addEventListener('change',async()=>{const row=box.querySelector(`select[data-feature-key="${CSS.escape(select.dataset.featureKey)}"][data-level="${select.dataset.level}"][data-choice-role="feat"]`);if(row){row.classList.toggle('hidden',!['feat','epic_boon'].includes(select.value));row.innerHTML='<option value="">'+(fr?'Choisir le don…':'Choose feat…')+'</option>'+(select.value==='epic_boon'?epicOptions:featOptions).map(o=>`<option value="${esc(o.value)}">${esc(o.label)}</option>`).join('');}if(select.value==='ability_score_improvement')await saveFeatureChoice(character.id,select.dataset.featureKey,Number(select.dataset.level),JSON.stringify({type:select.value}),{selection:'asi'});}));
box.querySelectorAll('select[data-choice-role="feat"]').forEach(select=>select.addEventListener('change',()=>{const type=box.querySelector(`select[data-feature-key="${CSS.escape(select.dataset.featureKey)}"][data-level="${select.dataset.level}"][data-choice-role="type"]`)?.value||'feat';saveFeatureChoice(character.id,select.dataset.featureKey,Number(select.dataset.level),JSON.stringify({type,feat:select.value}),{feat:select.value});}));
box.querySelectorAll('select:not([data-choice-role])').forEach(select=>select.addEventListener('change',()=>saveFeatureChoice(character.id,select.dataset.featureKey,Number(select.dataset.level),select.value)));}
let progressionRenderInProgress=false;let progressionRenderQueued=false;
async function renderProgression(){if(progressionRenderInProgress){progressionRenderQueued=true;return;}const box=document.querySelector('#progression-stats');if(!box||document.querySelector('#sheet-modal')?.classList.contains('hidden'))return;const name=document.querySelector('#sheet-name')?.value?.trim();const {data:{user}}=await progressionSupabase.auth.getUser();if(!user||!name)return;progressionRenderInProgress=true;try{const {data:character}=await progressionSupabase.from('characters').select('id,class_key,level,experience,hp_max,hp_current,hit_dice').eq('user_id',user.id).eq('name',name).maybeSingle();if(!character)return;const level=Number(document.querySelector('#sheet-level')?.value||character.level||1);const xp=Number(document.querySelector('#sheet-xp')?.value||character.experience||0);const classKey=character.class_key;const data=CLASS_DATA[classKey]||CLASS_DATA.fighter;const next=nextLevelInfo(level,xp);const con=Number(document.querySelector('#score-constitution')?.value||10);const hp=fixedHpMax(classKey,level,con);const lang=localStorage.getItem('preferredLanguage')||'en';const fr=lang==='fr';box.innerHTML=`<div class="progression-grid"><div><span>${fr?'Classe':'Class'}</span><strong>${CLASS_LABELS[lang][classKey]||classKey}</strong></div><div><span>${fr?'Dé de vie':'Hit die'}</span><strong>d${data.die}</strong></div><div><span>${fr?'Bonus de maîtrise':'Proficiency bonus'}</span><strong>+${2+Math.floor((level-1)/4)}</strong></div><div><span>${fr?'PV max calculés':'Calculated max HP'}</span><strong>${hp}</strong></div><div><span>${fr?'XP niveau actuel':'Current level XP'}</span><strong>${xpForLevel(level).toLocaleString()}</strong></div><div><span>${fr?'Prochain niveau':'Next level'}</span><strong>${next.next?`Lv ${next.next}`:'MAX'}</strong></div></div>${next.next?`<p class="progression-note">${next.remaining===0?(fr?'Niveau atteint.':'Level reached.'):(fr?`${next.remaining.toLocaleString()} XP avant le niveau ${next.next}.`:`${next.remaining.toLocaleString()} XP to level ${next.next}.`)}</p>`:''}`;let featureBox=document.querySelector('#progression-features');if(!featureBox){featureBox=document.createElement('div');featureBox.id='progression-features';box.insertAdjacentElement('afterend',featureBox);}await renderFeatureProgression(character,level,fr);const hitDice=document.querySelector('#sheet-hit-dice');if(hitDice)hitDice.value=`${level}d${data.die}`;}finally{progressionRenderInProgress=false;if(progressionRenderQueued){progressionRenderQueued=false;setTimeout(renderProgression,0);}}}
document.addEventListener('input',event=>{if(event.target.matches('#sheet-level,#sheet-xp,#score-constitution,#sheet-name'))renderProgression();});document.addEventListener('change',event=>{if(event.target.matches('#sheet-level,#sheet-xp,#score-constitution'))renderProgression();});const observer=new MutationObserver(()=>{if(!progressionRenderInProgress&&!progressionRenderQueued&&!document.querySelector('#sheet-modal')?.classList.contains('hidden')){progressionRenderQueued=true;setTimeout(()=>{progressionRenderQueued=false;renderProgression();},50);}});observer.observe(document.body,{childList:true,subtree:true});