(() => {
  const labels={en:{levelProgression:'Level progression',classResources:'Class resources',restRecovery:'Rest & recovery',shortRest:'☕ Short rest',longRest:'🌙 Long rest',derivedStats:'Derived stats',cantrip:'Cantrip',spellbook:'Spellbook',weaponMastery:'Weapon mastery'},fr:{levelProgression:'Progression du niveau',classResources:'Ressources de classe',restRecovery:'Repos et récupération',shortRest:'☕ Repos court',longRest:'🌙 Repos long',derivedStats:'Statistiques dérivées',cantrip:'Tour de magie',spellbook:'Livre de sorts',weaponMastery:'Maîtrise des armes'}};
  const classLabels={en:{barbarian:'Barbarian',bard:'Bard',cleric:'Cleric',druid:'Druid',fighter:'Fighter',monk:'Monk',paladin:'Paladin',ranger:'Ranger',rogue:'Rogue',sorcerer:'Sorcerer',warlock:'Warlock',wizard:'Wizard'},fr:{barbarian:'Barbare',bard:'Barde',cleric:'Clerc',druid:'Druide',fighter:'Guerrier',monk:'Moine',paladin:'Paladin',ranger:'Rôdeur',rogue:'Roublard',sorcerer:'Ensorceleur',warlock:'Occultiste',wizard:'Magicien'}};
  const speciesLabels={en:{aasimar:'Aasimar',dragonborn:'Dragonborn',dwarf:'Dwarf',elf:'Elf',gnome:'Gnome',goliath:'Goliath',halfling:'Halfling',human:'Human',orc:'Orc',tiefling:'Tiefling'},fr:{aasimar:'Aasimar',dragonborn:'Drakéide',dwarf:'Nain',elf:'Elfe',gnome:'Gnome',goliath:'Goliath',halfling:'Halfelin',human:'Humain',orc:'Orc',tiefling:'Tieffelin'}};
  const backgroundLabels={en:{acolyte:'Acolyte',artisan:'Artisan',charlatan:'Charlatan',criminal:'Criminal',entertainer:'Entertainer',guard:'Guard',farmer:'Farmer',guide:'Guide',hermit:'Hermit',noble:'Noble',merchant:'Merchant',sage:'Sage',sailor:'Sailor',soldier:'Soldier',scribe:'Scribe',wayfarer:'Wayfarer'},fr:{acolyte:'Acolyte',artisan:'Artisan',charlatan:'Charlatan',criminal:'Criminel',entertainer:'Artiste',guard:'Garde',farmer:'Fermier',guide:'Guide',hermit:'Ermite',noble:'Noble',merchant:'Marchand',sage:'Sage',sailor:'Marin',soldier:'Soldat',scribe:'Scribe',wayfarer:'Voyageur'}};
  const lang=()=>localStorage.getItem('preferredLanguage')||'en';
  const setText=(el,value)=>{if(el&&el.textContent!==value)el.textContent=value;};
  function translateStatic(){const l=labels[lang()];document.querySelectorAll('.section-heading h3').forEach(h=>{const raw=h.textContent.trim();const key=raw==='Level progression'||raw==='Progression du niveau'?'levelProgression':raw==='Class Resources'||raw==='Ressources de classe'?'classResources':raw==='Rest & Recovery'||raw==='Repos et récupération'?'restRecovery':raw==='Derived stats'||raw==='Statistiques dérivées'?'derivedStats':raw==='Weapon mastery'||raw==='Maîtrise des armes'?'weaponMastery':raw==='Spellbook'||raw==='Livre de sorts'?'spellbook':null;if(key)setText(h,l[key]);});setText(document.querySelector('#short-rest-button'),l.shortRest);setText(document.querySelector('#long-rest-button'),l.longRest);const ability=document.querySelector('#spellcasting-ability');if(ability){const map=lang()==='fr'?{'':'—',intelligence:'Intelligence',wisdom:'Sagesse',charisma:'Charisme'}:{'':'—',intelligence:'Intelligence',wisdom:'Wisdom',charisma:'Charisma'};[...ability.options].forEach(o=>setText(o,map[o.value]??o.textContent));}}
  function translateCatalogOptions(){const l=lang();document.querySelectorAll('#character-class option').forEach(o=>{if(classLabels[l][o.value])setText(o,classLabels[l][o.value]);});document.querySelectorAll('#character-species option').forEach(o=>{if(speciesLabels[l][o.value])setText(o,speciesLabels[l][o.value]);});document.querySelectorAll('#character-background option').forEach(o=>{if(backgroundLabels[l][o.value])setText(o,backgroundLabels[l][o.value]);});}
  function translateSpellRows(){const value=labels[lang()].cantrip;document.querySelectorAll('.spell-level option[value="0"]').forEach(o=>setText(o,value));}
  let languageSnapshot=null;
  function snapshot(){const form=document.querySelector('#sheet-form');if(!form)return null;return {values:Object.fromEntries([...form.querySelectorAll('input,select,textarea')].filter(e=>e.id||e.name).map(e=>[e.id||e.name,e.type==='checkbox'?e.checked:e.value]))};}
  function restore(s){if(!s?.values)return;Object.entries(s.values).forEach(([key,value])=>{const e=document.getElementById(key)||document.querySelector(`[name="${CSS.escape(key)}"]`);if(!e)return;if(e.type==='checkbox')e.checked=value;else e.value=value;});}
  document.addEventListener('click',event=>{if(event.target.closest('#sign-up-button')){event.preventDefault();event.stopImmediatePropagation();window.location.href='signup.html';}},true);
  document.addEventListener('click',event=>{if(event.target.closest('#language-toggle')){languageSnapshot=snapshot();setTimeout(()=>{translateStatic();translateCatalogOptions();translateSpellRows();restore(languageSnapshot);languageSnapshot=null;},0);}},true);
  const observer=new MutationObserver(()=>{translateStatic();translateCatalogOptions();translateSpellRows();});
  observer.observe(document.body,{childList:true,subtree:true});
  translateStatic();translateCatalogOptions();translateSpellRows();
})();
