(() => {
  const labels = {
    en: {
      levelProgression:'Level progression', classResources:'Class resources', restRecovery:'Rest & recovery', shortRest:'☕ Short rest', longRest:'🌙 Long rest', derivedStats:'Derived stats', cantrip:'Cantrip', choose:'Choose…', spellcasting:'Spellcasting ability', weaponMastery:'Weapon mastery', spellbook:'Spellbook'
    },
    fr: {
      levelProgression:'Progression du niveau', classResources:'Ressources de classe', restRecovery:'Repos et récupération', shortRest:'☕ Repos court', longRest:'🌙 Repos long', derivedStats:'Statistiques dérivées', cantrip:'Tour de magie', choose:'Choisir…', spellcasting:'Caractéristique d’incantation', weaponMastery:'Maîtrise des armes', spellbook:'Livre de sorts'
    }
  };
  const classLabels={en:{barbarian:'Barbarian',bard:'Bard',cleric:'Cleric',druid:'Druid',fighter:'Fighter',monk:'Monk',paladin:'Paladin',ranger:'Ranger',rogue:'Rogue',sorcerer:'Sorcerer',warlock:'Warlock',wizard:'Wizard'},fr:{barbarian:'Barbare',bard:'Barde',cleric:'Clerc',druid:'Druide',fighter:'Guerrier',monk:'Moine',paladin:'Paladin',ranger:'Rôdeur',rogue:'Roublard',sorcerer:'Ensorceleur',warlock:'Occultiste',wizard:'Magicien'}};
  const speciesLabels={en:{aasimar:'Aasimar',dragonborn:'Dragonborn',dwarf:'Dwarf',elf:'Elf',gnome:'Gnome',goliath:'Goliath',halfling:'Halfling',human:'Human',orc:'Orc',tiefling:'Tiefling'},fr:{aasimar:'Aasimar',dragonborn:'Drakéide',dwarf:'Nain',elf:'Elfe',gnome:'Gnome',goliath:'Goliath',halfling:'Halfelin',human:'Humain',orc:'Orc',tiefling:'Tieffelin'}};
  const backgroundLabels={en:{acolyte:'Acolyte',artisan:'Artisan',charlatan:'Charlatan',criminal:'Criminal',entertainer:'Entertainer',guard:'Guard',farmer:'Farmer',guide:'Guide',hermit:'Hermit',noble:'Noble',merchant:'Merchant',sage:'Sage',sailor:'Sailor',soldier:'Soldier',scribe:'Scribe',wayfarer:'Wayfarer'},fr:{acolyte:'Acolyte',artisan:'Artisan',charlatan:'Charlatan',criminal:'Criminel',entertainer:'Artiste',guard:'Garde',farmer:'Fermier',guide:'Guide',hermit:'Ermite',noble:'Noble',merchant:'Marchand',sage:'Sage',sailor:'Marin',soldier:'Soldat',scribe:'Scribe',wayfarer:'Voyageur'}};
  function lang(){return localStorage.getItem('preferredLanguage')||'en';}
  function text(el,value){if(el)el.textContent=value;}
  function translateStatic(){const l=labels[lang()];document.querySelectorAll('.section-heading h3').forEach(h=>{const raw=h.textContent.trim();if(raw==='Level progression'||raw==='Progression du niveau')text(h,l.levelProgression);else if(raw==='Class Resources'||raw==='Ressources de classe')text(h,l.classResources);else if(raw==='Rest & Recovery'||raw==='Repos et récupération')text(h,l.restRecovery);else if(raw==='Derived stats'||raw==='Statistiques dérivées')text(h,l.derivedStats);else if(raw==='Weapon mastery'||raw==='Maîtrise des armes')text(h,l.weaponMastery);else if(raw==='Spellbook'||raw==='Livre de sorts')text(h,l.spellbook);});text(document.querySelector('#short-rest-button'),l.shortRest);text(document.querySelector('#long-rest-button'),l.longRest);const ability=document.querySelector('#spellcasting-ability');if(ability){const map={en:{'':'—',intelligence:'Intelligence',wisdom:'Wisdom',charisma:'Charisma'},fr:{'':'—',intelligence:'Intelligence',wisdom:'Sagesse',charisma:'Charisme'}}[lang()];[...ability.options].forEach(o=>{if(map[o.value])o.textContent=map[o.value];});}}
  function translateCatalogOptions(){const l=lang();document.querySelectorAll('#character-class option').forEach(o=>{if(classLabels[l][o.value])o.textContent=classLabels[l][o.value];});document.querySelectorAll('#character-species option').forEach(o=>{if(speciesLabels[l][o.value])o.textContent=speciesLabels[l][o.value];});document.querySelectorAll('#character-background option').forEach(o=>{if(backgroundLabels[l][o.value])o.textContent=backgroundLabels[l][o.value];});document.querySelectorAll('.character-meta').forEach(el=>{const parts=el.textContent.split(' · ');if(parts.length===2)el.textContent=`${classLabels[l][parts[1]]||parts[1]} · ${speciesLabels[l][parts[0]]||parts[0]}`;});}
  function translateSpellRows(){const l=labels[lang()];document.querySelectorAll('.spell-level option[value="0"]').forEach(o=>o.textContent=l.cantrip);}
  let languageSnapshot=null;
  function snapshot(){const form=document.querySelector('#sheet-form');if(!form)return null;return {values:Object.fromEntries([...form.querySelectorAll('input,select,textarea')].filter(e=>e.id||e.name).map(e=>[e.id||e.name,e.type==='checkbox'?e.checked:e.value]))};}
  function restore(snapshot){if(!snapshot?.values)return;Object.entries(snapshot.values).forEach(([key,value])=>{const e=document.getElementById(key)||document.querySelector(`[name="${CSS.escape(key)}"]`);if(!e)return;if(e.type==='checkbox')e.checked=value;else e.value=value;});}
  document.addEventListener('click',event=>{if(event.target.closest('#sign-up-button')){event.preventDefault();event.stopImmediatePropagation();window.location.href='signup.html';}},true);
  document.addEventListener('click',event=>{if(event.target.closest('#language-toggle')){languageSnapshot=snapshot();setTimeout(()=>{translateStatic();translateCatalogOptions();translateSpellRows();restore(languageSnapshot);languageSnapshot=null;},0);}},true);
  const observer=new MutationObserver(()=>{translateStatic();translateCatalogOptions();translateSpellRows();});
  observer.observe(document.body,{childList:true,subtree:true});
  window.addEventListener('DOMContentLoaded',()=>{setTimeout(()=>{translateStatic();translateCatalogOptions();translateSpellRows();},50);});
})();
