(() => {
  const labels={en:{levelProgression:'Level progression',classResources:'Class resources',restRecovery:'Rest & recovery',shortRest:'☕ Short rest',longRest:'🌙 Long rest',derivedStats:'Derived stats',cantrip:'Cantrip',spellbook:'Spellbook',weaponMastery:'Weapon mastery'},fr:{levelProgression:'Progression du niveau',classResources:'Ressources de classe',restRecovery:'Repos et récupération',shortRest:'☕ Repos court',longRest:'🌙 Repos long',derivedStats:'Statistiques dérivées',cantrip:'Tour de magie',spellbook:'Livre de sorts',weaponMastery:'Maîtrise des armes'}};
  const classLabels={en:{barbarian:'Barbarian',bard:'Bard',cleric:'Cleric',druid:'Druid',fighter:'Fighter',monk:'Monk',paladin:'Paladin',ranger:'Ranger',rogue:'Rogue',sorcerer:'Sorcerer',warlock:'Warlock',wizard:'Wizard'},fr:{barbarian:'Barbare',bard:'Barde',cleric:'Clerc',druid:'Druide',fighter:'Guerrier',monk:'Moine',paladin:'Paladin',ranger:'Rôdeur',rogue:'Roublard',sorcerer:'Ensorceleur',warlock:'Occultiste',wizard:'Magicien'}};
  const speciesLabels={en:{aasimar:'Aasimar',dragonborn:'Dragonborn',dwarf:'Dwarf',elf:'Elf',gnome:'Gnome',goliath:'Goliath',halfling:'Halfling',human:'Human',orc:'Orc',tiefling:'Tiefling'},fr:{aasimar:'Aasimar',dragonborn:'Drakéide',dwarf:'Nain',elf:'Elfe',gnome:'Gnome',goliath:'Goliath',halfling:'Halfelin',human:'Humain',orc:'Orc',tiefling:'Tieffelin'}};
  const backgroundLabels={en:{acolyte:'Acolyte',artisan:'Artisan',charlatan:'Charlatan',criminal:'Criminal',entertainer:'Entertainer',guard:'Guard',farmer:'Farmer',guide:'Guide',hermit:'Hermit',noble:'Noble',merchant:'Merchant',sage:'Sage',sailor:'Sailor',soldier:'Soldier',scribe:'Scribe',wayfarer:'Wayfarer'},fr:{acolyte:'Acolyte',artisan:'Artisan',charlatan:'Charlatan',criminal:'Criminel',entertainer:'Artiste',guard:'Garde',farmer:'Fermier',guide:'Guide',hermit:'Ermite',noble:'Noble',merchant:'Marchand',sage:'Sage',sailor:'Marin',soldier:'Soldat',scribe:'Scribe',wayfarer:'Voyageur'}};
  const lang=()=>localStorage.getItem('preferredLanguage')||'en';
  const setText=(el,value)=>{if(el&&el.textContent!==value)el.textContent=value;};
  function translateStatic(){const l=labels[lang()];document.querySelectorAll('.section-heading h3').forEach(h=>{const raw=h.textContent.trim();const key=raw==='Level progression'||raw==='Progression du niveau'?'levelProgression':raw==='Class Resources'||raw==='Ressources de classe'?'classResources':raw==='Rest & Recovery'||raw==='Repos et récupération'?'restRecovery':raw==='Derived stats'||raw==='Statistiques dérivées'?'derivedStats':raw==='Weapon mastery'||raw==='Maîtrise des armes'?'weaponMastery':raw==='Spellbook'||raw==='Livre de sorts'?'spellbook':null;if(key)setText(h,l[key]);});setText(document.querySelector('#short-rest-button'),l.shortRest);setText(document.querySelector('#long-rest-button'),l.longRest);const ability=document.querySelector('#spellcasting-ability');if(ability){const map=lang()==='fr'?{'':'—',intelligence:'Intelligence',wisdom:'Sagesse',charisma:'Charisme'}:{'':'—',intelligence:'Intelligence',wisdom:'Wisdom',charisma:'Charisma'};[...ability.options].forEach(o=>setText(o,map[o.value]??o.textContent));}}
  function translateCatalogOptions(){const l=lang();document.querySelectorAll('#character-class option').forEach(o=>{if(classLabels[l][o.value])setText(o,classLabels[l][o.value]);});document.querySelectorAll('#character-species option').forEach(o=>{if(speciesLabels[l][o.value])setText(o,speciesLabels[l][o.value]);});document.querySelectorAll('#character-background option').forEach(o=>{if(backgroundLabels[l][o.value])setText(o,backgroundLabels[l][o.value]);});}
  function translateSpellRows(){const value=labels[lang()].cantrip;document.querySelectorAll('.spell-level option[value="0"]').forEach(o=>setText(o,value));}
  let languageSnapshot=null;
  function snapshot(){const form=document.querySelector('#sheet-form');if(!form)return null;return {values:Object.fromEntries([...form.querySelectorAll('input,select,textarea')].filter(e=>e.id||e.name).map(e=>[e.id||e.name,e.type==='checkbox'?e.checked:e.value]))};}
  function restore(s){if(!s?.values)return;Object.entries(s.values).forEach(([key,value])=>{const e=document.getElementById(key)||document.querySelector(`[name="${CSS.escape(key)}"]`);if(!e)return;if(e.type==='checkbox')e.checked=value;else e.value=value;});}
  document.addEventListener('click',event=>{if(event.target.closest('#sign-up-button')){event.preventDefault();event.stopImmediatePropagation();window.location.href='signup.html';}},true);
  document.addEventListener('click',event=>{if(event.target.closest('#language-toggle')){languageSnapshot=snapshot();setTimeout(()=>{translateStatic();translateCatalogOptions();translateSpellRows();restore(languageSnapshot);languageSnapshot=null;},0);}},true);
  const observer=new MutationObserver(()=>{translateStatic();translateCatalogOptions();translateSpellRows();decorateCharacterCards();});
  observer.observe(document.body,{childList:true,subtree:true});
  translateStatic();translateCatalogOptions();translateSpellRows();

  const PORTRAIT_ENDPOINT='https://wmeuebjbvoqudhpwtxyn.supabase.co/functions/v1/generate-character-portrait';
  const supa=()=>window.supabaseClient||window.supabase||null;
  async function generatePortrait(characterId){const c=supa();if(!c?.auth||!characterId)return null;const {data:{session}}=await c.auth.getSession();if(!session)return null;const r=await fetch(PORTRAIT_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({character_id:characterId})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Portrait generation failed');return d;}
  function portraitStyle(){if(document.getElementById('character-portrait-style'))return;const s=document.createElement('style');s.id='character-portrait-style';s.textContent='.character-portrait-thumb{width:64px;height:64px;border-radius:10px;object-fit:cover;background:#151922;display:block}.character-portrait-large{width:260px;height:340px;border-radius:14px;object-fit:cover;background:#151922;display:block}.portrait-status{font-size:.8rem;opacity:.7}.portrait-card-wrap{display:flex;align-items:center;gap:10px;margin-bottom:8px}.portrait-generate-button{font-size:.8rem}';document.head.appendChild(s);}
  async function getCharacter(id){const c=supa();if(!c?.from)return null;const {data}=await c.from('characters').select('id,name,portrait_url').eq('id',id).maybeSingle();return data||null;}
  async function decorateCharacterCards(){const buttons=[...document.querySelectorAll('.sheet-open-button[data-character-id]')];if(!buttons.length)return;portraitStyle();for(const button of buttons){const card=button.closest('.character-card');if(!card||card.querySelector('.character-portrait-thumb'))continue;const character=await getCharacter(button.dataset.characterId);if(!character?.portrait_url)continue;const wrap=document.createElement('div');wrap.className='portrait-card-wrap';const img=document.createElement('img');img.className='character-portrait-thumb';img.src=character.portrait_url;img.alt='Character portrait';wrap.appendChild(img);const title=card.querySelector('h2');if(title)title.before(wrap);else card.prepend(wrap);}}
  async function showSheetPortrait(id){const character=await getCharacter(id);if(!character)return;portraitStyle();const modal=document.querySelector('#sheet-modal');if(!modal)return;let host=modal.querySelector('#character-portrait-panel');if(!host){host=document.createElement('div');host.id='character-portrait-panel';host.style.cssText='display:flex;flex-direction:column;align-items:center;gap:6px;margin:8px 0 14px;';const form=modal.querySelector('#sheet-form')||modal.firstElementChild;form?.prepend(host);}host.innerHTML='';if(character.portrait_url){const img=document.createElement('img');img.className='character-portrait-large';img.src=character.portrait_url;img.alt='Character portrait';host.appendChild(img);}else{const status=document.createElement('div');status.className='portrait-status';status.textContent=lang()==='fr'?'Aucun portrait généré pour le moment.':'No portrait generated yet.';host.appendChild(status);}}
  document.addEventListener('click',event=>{const button=event.target.closest('.sheet-open-button[data-character-id]');if(button)setTimeout(()=>showSheetPortrait(button.dataset.characterId),100);},true);
  window.generateCharacterPortrait=generatePortrait;window.attachCharacterPortrait=async(id)=>showSheetPortrait(id);
  window.queueCharacterPortraitGeneration=async function(characterId){try{const result=await generatePortrait(characterId);if(result?.image_url){document.querySelectorAll(`[data-character-portrait="${characterId}"]`).forEach(e=>{e.src=result.image_url;e.style.display='block';});await decorateCharacterCards();await showSheetPortrait(characterId);}return result;}catch(e){console.warn('[portrait]',e);return null;}};
})();
